### PR TITLE
fix: typo

### LINKED ISSUE #14: Throwing error due to missing commas on lines 176 and 177
Missing commas for the newly added capital cities on 176 and 177 after the word "true" is causing a lua error.

DMFQuest/DMFQuest.lua:1 DMFQuest/DMFQuest.lua:178: '}' expected (to close '{' at line 163) near '[

### PR DESCRIPTION
**Pull request by paulbuechner**
closes #14, #15

### CODE REVIEW

**Comment by ahakola** [comment]
Thanks for the effort, but I saw this after I had already pushed fix from my end :(

**Comment by paulbuechner** [comment]
Please have a look at my PM on CurseForge for german localization.

**Comment by ahakola** [comment]
Do you feel like your localization is so complete that I should hard code it to the addon instead of using the Curseforge localization tool, or should you just import your translations to the Curseforge? I can also import those, but then I will be credited with the translations instead of you in the system.

If you choose importing
- Go to https://legacy.curseforge.com/wow/addons/dmfquest/localization/import-lua
- Leave Namespace as `-` (except unless you are translating the `Notes` from .toc-file, that goes under `TOC` -namespace)
- Language `deDE`
- Format `table additions`
- Missing Phrase Handling leave as `Do nothing`
- And then copy and paste your translations to the textbox under and press `Import`

Edit: And let me know you have updated the translations so I can push out new version with proper translations!

**Comment by paulbuechner** [comment]
I dont care about credits or anything. I just did them along fixing the other issue.

At the end i didn't include them in the PR as I saw u using another tool providing the locals. Feel free to handle them your way!

**Pull request closed without merging**
